### PR TITLE
smtp: fix regression in address type validation

### PR DESCRIPTION
**Pull request by zackschuster**
in my zeal, i changed truthy checks that allowed arrays for recipients to hard type checks. this PR adds array checks to validation, as well as tests to prevent future regressions.

### CODE REVIEW

**Comment by eleith** [comment]
lgtm, let me know when this is out of draft

**Comment by zackschuster** [comment]
@eleith i think this is ready but i need to test in azure a bit more before i'm confident

**Comment by eleith** [comment]
@zackschuster it looks good to me on the surface.

**Comment by zackschuster** [comment]
@eleith ready

**Comment by eleith** [comment]
@zackschuster i went ahead and merged it. fyi.

**Comment by zackschuster** [comment]
@eleith yes, i wanted that. thank you :)

**Pull request merged**
