### PR TITLE
migrate to typescript & node.js-compatible es modules

### PR DESCRIPTION
**Pull request by zackschuster**
- [x] port to node.js-compatible es modules
- [x] port to typescript
- [ ] reconfigure rollup
- [ ] fix tests
- [ ] point `main` to either cjs rollup bundle or esm source (prob cjs)

### CODE REVIEW

**Comment by eleith** [comment]
looking good. 

i'm also open to seeing this project move to typescript if that helps with big changes like this to prevent regressions.

**Comment by zackschuster** [comment]
i wouldn't mind doing the port job to typescript. i'd also move the test suite to [ava](https://github.com/avajs/ava), which i have experience in using with typescript.

**Comment by zackschuster** [comment]
PR is in typescript now. made a few (relatively) minor API changes (like condensing error codes into a const enum & getting rid of legacy code that said "will remove at some point"), since i'm pretty sure this will end up semver major no matter what.

**Comment by eleith** [comment]
> i wouldn't mind doing the port job to typescript. i'd also move the test suite to [ava](https://github.com/avajs/ava), which i have experience in using with typescript.

why ava vs jest?

**Comment by zackschuster** [comment]
technically, they have a pretty similar feature set & both are written with current tools. the breaker for me is that jest is a facebook project, whereas ava is community-led (started by sindresorhus).

**Comment by zackschuster** [comment]
also it looks like we'd have to install `@types/jest`, whereas ava has types built-in: https://swizec.com/blog/the-big-mac-index-and-jest-fetch-testing/swizec/9187

(coincidentally i've [already tested fetch with ava](https://github.com/zackschuster/ng-app/blob/master/test/-register.js#L26))

**Comment by zackschuster** [comment]
esm in node will probably ship unflagged on 12.x in april. i'll try to finish this around then.

**Comment by zackschuster** [comment]
tests are failing locally due to smtp server issues. image attached for reference:
image

**Comment by zackschuster** [comment]
i think the above might be due to changes i made during conversion. i'm going through the shipped code to repair differences.

side note: node 14 today! hooray for unflagged modules! fun fact: [the flag almost wasn't removed & node's tsc was surprised to see it happen](https://github.com/nodejs/node/pull/31974)

**Comment by zackschuster** [comment]
[modules are still considered experimental](https://medium.com/@nodejs/node-js-version-14-available-now-8170d384567e#2368), so i feel less bad about not landing this in time with the launch >D

**Comment by eleith** [comment]
@zackschuster looking good. i've given you direct access to the project in reflection of your contribution to the project. fyi, a few of the outdated dependencies for emailjs are throwing up security alerts on github for this project, so perhaps those can get addressed during this upgrade.

**Comment by zackschuster** [comment]
thank you! :D i'll see if i can move the PR from my fork to a local branch without breaking things.

for `addressparser`, would you like to switch to [emailjs-addressparser](https://www.npmjs.com/package/emailjs-addressparser)?

**Comment by eleith** [comment]
depends on the effort level, if it is transparent, sure.

**Comment by zackschuster** [comment]
closing in favor of #246

**Pull request closed without merging**
