### PR TITLE
feat: return promise from Message read

### PR DESCRIPTION
**Pull request by CarsonF**
I want to use this library to build mime messages that I'll send to AWS SES directly. This makes it easier to get the built message back.

### CODE REVIEW

**Comment by CarsonF** [comment]
How's it a breaking change? Both work:
```ts
message.read((err, data) => { ... });
await message.read();
```

**Comment by zackschuster** [comment]
Because it modifies the API signature. Technically this could be resolved by only returning a promise if `callback == null` — since that's an overload, not a modification — but, as mentioned before, the pattern established in `SMTPClient` demands we go with a separate `readAsync` method.

**Review by zackschuster — CHANGES_REQUESTED** [review]
Please follow the pattern in [SMTPClient#sendAsync](https://github.com/eleith/emailjs/blob/main/smtp/client.ts#L77), where we manually wrap the method in a promise:

```ts
public readAsync() {
	return new Promise<string>((resolve, reject) => {
		this.read((err, buffer) => {
			if (err != null) {
				reject(err);
			} else {
				resolve(buffer);
			}
		});
	});
}
```

**Review by zackschuster — APPROVED** [review]

**Comment by zackschuster** [comment]
Thank you! 😄

**Comment by zackschuster** [comment]
@CarsonF this (as well as your other PR) should be live as of `v3.6.0` 😄

**Comment by CarsonF** [comment]
Already all over it. Thanks @zackschuster!!

**Pull request merged**
