### PR TITLE
inline address parsing

### PR DESCRIPTION
**Pull request by zackschuster**
reduces bundle size from 2157 -> 2083 loc

### CODE REVIEW

**Comment by zackschuster** [comment]
@eleith i'm done code-golfing :) assuming you're fine with merging, i think we can ship 3.1 after this.

**Comment by eleith** [comment]
3.1 has been published on npm

**Comment by zackschuster** [comment]
did that have the updated bundles?

**Comment by eleith** [comment]
oops. no, i don't think i have any hooks. i'll re-run.

**Comment by eleith** [comment]
3.2 has been published to npm with bundles included

**Pull request merged**
