### PR TITLE
bump to 3.0 and build bundles

### PR DESCRIPTION
**Pull request by eleith**
address #250

### CODE REVIEW

**Comment by zackschuster** [comment]
output is the same with the latest version of rollup. i'll tag `master` with `v3.0.0` after this lands, and then push the dependency updates.

**Comment by zackschuster** [comment]
it occurs to me the old bundle will still be published. i can think of one reason why someone might want it.

**Comment by eleith** [comment]
@zackschuster fyi, https://www.npmjs.com/package/emailjs

let me know if you find anything and we need to re-publish

**Comment by zackschuster** [comment]
woohoo! thank you :D

**Comment by zackschuster** [comment]
https://github.com/eleith/emailjs/tree/v3.0.0

**Pull request merged**
