### PR TITLE
Allow references and in-reply-to header support

### PR DESCRIPTION
**Pull request by rafalneves**
Added references and in-reply-to header support. For example:

```
	var message = {
		text: "Hi",
		from: "example@email.com",
		to: "me me@example.com",
		inReplyTo: "1234@example.com",
		references: ["1232@example.com","1233@example.com","1234@example.com"],
		subject: "References and/or in-reply-to support"
	};

```
This way the sended message should contain:
```
	In-Reply-To: <1234@example.com>
	References: <1232@example.com>, <1233@example.com>, <1234@example.com>

```

### CODE REVIEW

**Comment by eleith** [comment]
reading this, it seems like in-reply-to and references should contain message-ids and not email addresses: https://afterlogic.com/mailbee-net/docs/set_from_and_other_headers.html#ReplyToMessage

**Comment by eleith** [comment]
this has impact on this PR, because you are adding `<` and `<` around all the values that are to be passed into this. how about modifying the PR such that the values are added in directly and the user can decide how to format the headers themselves?

**Comment by rafalneves** [comment]
I meant 1232@example.com, 1233@example.com, etc... as examples of message-ids. But yes, was an unhappy choosing of examples...

Regarding the second comment, are you talking about a feature to allow any user created headers and just dump the value of them into the stream?

**Comment by rafalneves** [comment]
Oh... yeah... right. Would only accept email like references.

Yes, it would accomplish the same. The only thing that I'm doing is specify those headers and provide a more structured and restrictive API for them. Yeah this PR premise is invalid. Reject it, pls.

So, just to clarify, one example of this "current" feature usage would be:

```
var message = {
		text: "Hi",
		from: "example@email.com",
		to: "me me@example.com",
		"in-reply-to": "<43ba2629-00f9-fab3-fb4c-08e62a86c66f@example.com>",
		references:  "<43ba2629-00f9-fab3-fb4c-08e62a86c66f@example.com>, <43ba2629-00f9-fab3-fb4c-08e62a86c66e@example.com>",
		subject: "References and/or in-reply-to support"
	};
```

Right?

**Comment by eleith** [comment]
correct. that should work!

**Pull request closed without merging**
