### PR TITLE
Update messages

### PR DESCRIPTION
**Pull request by JoelSebstn**
Thanks for this wonderful package  , here in this  file I am getting an error . Hope you accept this. Kudos to the more packages like this

### CODE REVIEW

**Comment by zackschuster** [comment]
thanks for the pr! can you elaborate on what error you're getting?

**Comment by JoelSebstn** [comment]
When installing the package -
npm install emailjs
We guys are getting the error as in the attachment,but can be solved by a
small edit as my pull

**Comment by JoelSebstn** [comment]
error:-{
"resource": "/d:/Memlo/memlo-api/node_modules/emailjs/smtp/message.ts",
"owner": "typescript",
"code": "1192",
"severity": 8,
"message": "Module '\"fs\"' has no default export.",
"source": "ts",
"startLineNumber": 1,
"startColumn": 8,
"endLineNumber": 1,
"endColumn": 10
}
message- Module '"fs"' has no default export.

**Comment by zackschuster** [comment]
ah, a compiler error. you simply need to enable `esModuleInterop` or `allowSyntheticDefaultImports`. this is stated in the readme.

**Comment by zackschuster** [comment]
closing as not a bug :)

**Pull request closed without merging**
